package com.cmp.main.view.record.yinhua
 
import com.cmp.main.model.YinHuaPrice;
import com.cmp.core.common.StringUtil;


rule "zhengpian"
   	salience 100  
    lock-on-active true 
    when
        $yinHuaPrice:YinHuaPrice(type.equals("按整片"))
    then
        $yinHuaPrice.setShangxianjiage( $yinHuaPrice.getZhengpianPrice());
end


rule "mianji"
   	salience 100  
    lock-on-active true 
    when
        $yinHuaPrice:YinHuaPrice(type.equals("按面积"))
    then
       
		Double mianjiPrice =  $yinHuaPrice.getMianjiPrice();
		if(mianjiPrice==null){
			System.err.println("rules.yinhua.mianji:没有设置单位面积的价格");
			return;
		}
		Double chang = $yinHuaPrice.getChang();
		Double kuan = $yinHuaPrice.getKuan();
	
		double mianji = StringUtil.round(StringUtil.mul(chang.doubleValue(), kuan.doubleValue()),2);
        $yinHuaPrice.setShangxianjiage(StringUtil.round(StringUtil.mul(mianji, mianjiPrice.doubleValue()),2));
        $yinHuaPrice.setBasePrice(mianjiPrice);
end


rule "zhongliang"
   	salience 100  
    lock-on-active true 
    when
        $yinHuaPrice:YinHuaPrice(type.equals("按公斤"))
    then
        //单位公斤的价格
        Double zhongliangPrice = $yinHuaPrice.getZhongliangPrice();
        //重量
        //Double zhongliang = $yinHuaPrice.getZhongliang();
        Double zhongliang = 1.0;
        if(zhongliangPrice==null || zhongliang==null){
			System.err.println("rules.yinhua.zhongliang:没有设置单位重量的价格");
			return;
		}
		//设置上限价格
		$yinHuaPrice.setShangxianjiage( StringUtil.round(StringUtil.mul(zhongliang.doubleValue(), zhongliangPrice.doubleValue()),2));
		//设置基础价格
		$yinHuaPrice.setBasePrice(zhongliangPrice);
       
end

rule "changdu"
   	salience 100  
    lock-on-active true 
    when
        $yinHuaPrice:YinHuaPrice(type.equals("按长度"))
    then
        //单位长度的价格
        Double changduPrice = $yinHuaPrice.getChangduPrice();
        //长度
        //Double chang = $yinHuaPrice.getChang();
        Double chang = 1.0;
        if(changduPrice==null || chang==null){
			System.err.println("rules.yinhua.changdu:没有设置单位长度的价格");
			return;
		}
		//设置上限价格
		$yinHuaPrice.setShangxianjiage( StringUtil.round(StringUtil.mul(chang.doubleValue(), changduPrice.doubleValue()),2));
		//设置基础价格
		$yinHuaPrice.setBasePrice(changduPrice);
       
end

rule "yuanmi"
   	salience 100  
    lock-on-active true 
    when
        $yinHuaPrice:YinHuaPrice(type.equals("按元/米"))
    then
        //单位长度的价格,元/米
        Double yuanmiPrice = $yinHuaPrice.getYuanmiPrice();
        //长度
        //Double chang = $yinHuaPrice.getChang();
        Double chang = 1.0;
        if(yuanmiPrice==null || chang==null){
			System.err.println("rules.yinhua.changdu:没有设置单位长度的价格");
			return;
		}
		//设置上限价格
		$yinHuaPrice.setShangxianjiage( StringUtil.round(StringUtil.mul(chang.doubleValue(), yuanmiPrice.doubleValue()),2));
		//设置基础价格
		$yinHuaPrice.setBasePrice(yuanmiPrice);
       
end


rule "chicun1"
   	salience 100  
    lock-on-active true 
    when
        $yinHuaPrice:YinHuaPrice(type.equals("按尺寸"),chicun<5)
    then
       
        int banshu = $yinHuaPrice.getBanshu();
        
        Double zPrice = $yinHuaPrice.getZ5Price();
       
        Double basePrice = $yinHuaPrice.getP5Price();
        if(zPrice==null || basePrice==null){
        	System.err.println("rules.yinhua.mianji:没有设置该尺寸的价格");
			return;
        }
        double sxjg = StringUtil.round(StringUtil.add(basePrice,StringUtil.mul(zPrice,(banshu-1))),2);
        $yinHuaPrice.setShangxianjiage(sxjg);
        $yinHuaPrice.setBasePrice(basePrice);
        $yinHuaPrice.setZengjiayisejiage(zPrice);
end

//5-10CM
rule "chicun2"
   	salience 100  
    lock-on-active true 
    when
        $yinHuaPrice:YinHuaPrice(type.equals("按尺寸"),chicun>=5,chicun<10)
    then
        //版数
        int banshu = $yinHuaPrice.getBanshu();
        //增加一色的单价
        Double zPrice = $yinHuaPrice.getZ10Price();
        //基础价格
        Double basePrice = $yinHuaPrice.getP10Price();
        if(zPrice==null || basePrice==null){
        	System.err.println("rules.yinhua.mianji:没有设置该尺寸的价格");
			return;
        }
        double sxjg = StringUtil.round(StringUtil.add(basePrice,StringUtil.mul(zPrice,(banshu-1))),2);
        $yinHuaPrice.setShangxianjiage(sxjg);
        $yinHuaPrice.setBasePrice(basePrice);
        $yinHuaPrice.setZengjiayisejiage(zPrice);
end

//10-20CM
rule "chicun3"
   	salience 100  
    lock-on-active true 
    when
        $yinHuaPrice:YinHuaPrice(type.equals("按尺寸"),chicun>=10,chicun<20)
    then
        //版数
        int banshu = $yinHuaPrice.getBanshu();
        //增加一色的单价
        Double zPrice = $yinHuaPrice.getZ20Price();
        //基础价格
        Double basePrice = $yinHuaPrice.getP20Price();
        if(zPrice==null || basePrice==null){
        	System.err.println("rules.yinhua.mianji:没有设置该尺寸的价格");
			return;
        }
        double sxjg = StringUtil.round(StringUtil.add(basePrice,StringUtil.mul(zPrice,(banshu-1))),2);
        $yinHuaPrice.setShangxianjiage(sxjg);
        $yinHuaPrice.setBasePrice(basePrice);
        $yinHuaPrice.setZengjiayisejiage(zPrice);
end

//20-30CM
rule "chicun4"
   	salience 100  
    lock-on-active true 
    when
        $yinHuaPrice:YinHuaPrice(type.equals("按尺寸"),chicun>=20,chicun<30)
    then
        //版数
        int banshu = $yinHuaPrice.getBanshu();
        //增加一色的单价
        Double zPrice = $yinHuaPrice.getZ30Price();
        //基础价格
        Double basePrice = $yinHuaPrice.getP30Price();
        if(zPrice==null || basePrice==null){
        	System.err.println("rules.yinhua.mianji:没有设置该尺寸的价格");
			return;
        }
        double sxjg = StringUtil.round(StringUtil.add(basePrice,StringUtil.mul(zPrice,(banshu-1))),2);
        $yinHuaPrice.setShangxianjiage(sxjg);
        $yinHuaPrice.setBasePrice(basePrice);
        $yinHuaPrice.setZengjiayisejiage(zPrice);
end

//30-40CM
rule "chicun5"
   salience 100  
    lock-on-active true 
    when
        $yinHuaPrice:YinHuaPrice(type.equals("按尺寸"),chicun>=30,chicun<40)
    then
        //版数
        int banshu = $yinHuaPrice.getBanshu();
        //增加一色的单价
        Double zPrice = $yinHuaPrice.getZ40Price();
        //基础价格
        Double basePrice = $yinHuaPrice.getP40Price();
        if(zPrice==null || basePrice==null){
        	System.err.println("rules.yinhua.mianji:没有设置该尺寸的价格");
			return;
        }
        double sxjg = StringUtil.round(StringUtil.add(basePrice,StringUtil.mul(zPrice,(banshu-1))),2);
        $yinHuaPrice.setShangxianjiage(sxjg);
        $yinHuaPrice.setBasePrice(basePrice);
        $yinHuaPrice.setZengjiayisejiage(zPrice);
end

//40-50CM
rule "chicun6"
   salience 100  
    lock-on-active true 
    when
        $yinHuaPrice:YinHuaPrice(type.equals("按尺寸"),chicun>=40,chicun<50)
    then
        //版数
        int banshu = $yinHuaPrice.getBanshu();
        //增加一色的单价
        Double zPrice = $yinHuaPrice.getZ50Price();
        //基础价格
        Double basePrice = $yinHuaPrice.getP50Price();
        if(zPrice==null || basePrice==null){
        	System.err.println("rules.yinhua.mianji:没有设置该尺寸的价格");
			return;
        }
       double sxjg = StringUtil.round(StringUtil.add(basePrice,StringUtil.mul(zPrice,(banshu-1))),2);
        $yinHuaPrice.setShangxianjiage(sxjg);
        $yinHuaPrice.setBasePrice(basePrice);
        $yinHuaPrice.setZengjiayisejiage(zPrice);
end

//50cm以上
rule "chicun7"
   	salience 100  
    lock-on-active true 
    when
        $yinHuaPrice:YinHuaPrice(type.equals("按尺寸"),chicun>=50)
    then
        //版数
        int banshu = $yinHuaPrice.getBanshu();
        //增加一色的单价
        Double zPrice = $yinHuaPrice.getzMaxPrice();
        //基础价格
        Double basePrice = $yinHuaPrice.getpMaxPrice();
        if(zPrice==null || basePrice==null){
        	System.err.println("rules.yinhua.mianji:没有设置该尺寸的价格");
			return;
        }
       double sxjg = StringUtil.round(StringUtil.add(basePrice,StringUtil.mul(zPrice,(banshu-1))),2);
        $yinHuaPrice.setShangxianjiage(sxjg);
        $yinHuaPrice.setBasePrice(basePrice);
        $yinHuaPrice.setZengjiayisejiage(zPrice);
end

//最后计算，是否圆筒，0.05元每片
rule "shifouyuantong"
	salience 99  
    lock-on-active true 
    when
        $yinHuaPrice:YinHuaPrice(!StringUtil.isEmpty(shifouyuantong),shifouyuantong.equals("是"))
    then
        //上限价格
        double shangxianjiage = 0.0;
        //第一级上限价格
        Double firstShangxianjiage = $yinHuaPrice.getShangxianjiage();
        if(firstShangxianjiage==null || firstShangxianjiage.doubleValue()<0.0){
        	$yinHuaPrice.setShangxianjiage(null);
        	System.err.println("rules.yinhua.shifouyuantong:第一级上限价格为空");
        	return;
        }
        //+0.05
        shangxianjiage = StringUtil.add(firstShangxianjiage,0.05);
        //保留2位小数
        shangxianjiage = StringUtil.round(shangxianjiage,2);
        $yinHuaPrice.setShangxianjiage(shangxianjiage);
end