package com.cmp.main.view.record.shuixi
 
import com.cmp.main.model.Record;
import com.cmp.core.common.StringUtil;

//针织类别的上限价格
function boolean isZhenZhi(String leibie){
	 if(StringUtil.isEmpty(leibie)){
	 	return false;
	 }
	 return leibie.equals("针织");
}
//小数精确位数
function int getXiaoShu(){
	return 2;
}
//计算上限价格
function Double getShangXianJiaGe(Record record,double price){
	 	//针织特殊处理价格
	 	double teshuchulijiage = 0.0;
	 	if(record.getTeshuchulijiage()!=null){
	 		teshuchulijiage = record.getTeshuchulijiage();
	 	}
       	//衣服重量
       	double yifuzhongliang =  record.getYifuzhongliang();
       	if(yifuzhongliang<=0){
       		System.err.println("rules.shuixi.zhenzhi:衣服重量小于等于0");
       		return null;
       	}
       	 //上限价格
        double shangxianjiage = 0.0;
        //单价
       	shangxianjiage = StringUtil.add(StringUtil.mul(price,yifuzhongliang),teshuchulijiage);
       	//保留两位小数
       	return StringUtil.round(shangxianjiage,getXiaoShu());
}
//普通水洗
rule "zhenzhileibie1"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isZhenZhi(shuixileibie),!StringUtil.isEmpty(zhenzhileibie),zhenzhileibie.equals("普通水洗"))
    then
        //普通水洗3元/KG
        $record.setShangxianjiage(getShangXianJiaGe($record,3.0));
end

//普通水洗+吊干
rule "zhenzhileibie2"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isZhenZhi(shuixileibie),!StringUtil.isEmpty(zhenzhileibie),zhenzhileibie.equals("普通水洗+吊干"))
    then
        //普通水洗+吊干 4元/KG
        $record.setShangxianjiage(getShangXianJiaGe($record,4.0));
end

//重水洗
rule "zhenzhileibie3"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isZhenZhi(shuixileibie),!StringUtil.isEmpty(zhenzhileibie),zhenzhileibie.equals("重水洗"))
    then
        //重水洗 4元/KG
        $record.setShangxianjiage(getShangXianJiaGe($record,4.0));
end

//硅油洗
rule "zhenzhileibie4"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isZhenZhi(shuixileibie),!StringUtil.isEmpty(zhenzhileibie),zhenzhileibie.equals("硅油洗"))
    then
        //硅油洗 4元/KG
        $record.setShangxianjiage(getShangXianJiaGe($record,4.0));
end

//酵素洗
rule "zhenzhileibie5"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isZhenZhi(shuixileibie),!StringUtil.isEmpty(zhenzhileibie),zhenzhileibie.equals("酵素洗"))
    then
        //酵素洗 4.2元/KG
        $record.setShangxianjiage(getShangXianJiaGe($record,4.2));
end

//酵漂洗
rule "zhenzhileibie6"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isZhenZhi(shuixileibie),!StringUtil.isEmpty(zhenzhileibie),zhenzhileibie.equals("酵漂洗"))
    then
        //酵漂洗 6.5元/KG
        $record.setShangxianjiage(getShangXianJiaGe($record,6.5));
end

//柔软洗
rule "zhenzhileibie7"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isZhenZhi(shuixileibie),!StringUtil.isEmpty(zhenzhileibie),zhenzhileibie.equals("柔软洗"))
    then
        //柔软洗 3.5元/KG
        $record.setShangxianjiage(getShangXianJiaGe($record,3.5));
end

//石磨洗
rule "zhenzhileibie8"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isZhenZhi(shuixileibie),!StringUtil.isEmpty(zhenzhileibie),zhenzhileibie.equals("石磨洗"))
    then
        //石磨洗 5元/KG
        $record.setShangxianjiage(getShangXianJiaGe($record,5.0));
end

//碱洗
rule "zhenzhileibie9"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isZhenZhi(shuixileibie),!StringUtil.isEmpty(zhenzhileibie),zhenzhileibie.equals("碱洗"))
    then
        //碱洗 5元/KG
        $record.setShangxianjiage(getShangXianJiaGe($record,5.0));
end

//碱石洗
rule "zhenzhileibie10"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isZhenZhi(shuixileibie),!StringUtil.isEmpty(zhenzhileibie),zhenzhileibie.equals("碱石洗"))
    then
        //碱石洗 5.5元/KG
        $record.setShangxianjiage(getShangXianJiaGe($record,5.5));
end