package com.cmp.main.view.record.dingxing
 
import com.cmp.main.model.Record;
import com.cmp.core.common.StringUtil;

function boolean isTrue(String str){
	if(!StringUtil.isEmpty(str) && str.equals("是")){
    	return true;
    }
    return false;
}
function boolean isFalse(String str){
	if(!StringUtil.isEmpty(str) && str.equals("否")){
    	return true;
    }
    return false;
}

//毛圈
rule "maouan"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(jianmaopibupinzhong.equals("毛圈"))
    then
       $record.setBasePrice(1.0);
end

//汗布
rule "hanbu"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(jianmaopibupinzhong.equals("汗布"))
    then
       $record.setBasePrice(1.6);
end

//剪毛
rule "jianmao"
   	salience 99  
    lock-on-active true 
    when
         $record:Record(jianmaojiagongleibie1.equals("剪毛"))
    then
        //基础价格
        Double basePrice = $record.getBasePrice();
        if(basePrice==null){
        	System.err.println("rules.jianmao.jianmao:基础价格为null");
        	return;
        }
        double shangxianjiage = 0.0;
        shangxianjiage = StringUtil.mul(basePrice.doubleValue(),1.0);
        //保留2位小数
        shangxianjiage = StringUtil.round(shangxianjiage,2);
        $record.setShangxianjiage(shangxianjiage);
end

//先起毛（起绒）后剪毛
rule "xianqizaijian"
   	salience 99  
    lock-on-active true 
    when
         $record:Record(jianmaojiagongleibie1.equals("先起毛（起绒）后剪毛"))
    then
        //基础价格
        Double basePrice = $record.getBasePrice();
        if(basePrice==null){
        	System.err.println("rules.jianmao.xianqizaijian:基础价格为null");
        	return;
        }
        double shangxianjiage = 0.0;
        shangxianjiage = StringUtil.mul(basePrice.doubleValue(),1.2);
        //保留2位小数
        shangxianjiage = StringUtil.round(shangxianjiage,2);
        $record.setShangxianjiage(shangxianjiage);
end

//一面剪毛
rule "yimianjianmao"
   	salience 98  
    lock-on-active true 
    when
         $record:Record(jianmaojiagongleibie2.equals("一面剪毛"))
    then
         //上限价格
        double shangxianjiage = 0.0;
        //第一级上限价格
        Double firstShangxianjiage = $record.getShangxianjiage();
        if(firstShangxianjiage==null || firstShangxianjiage.doubleValue()<0.0){
        	$record.setShangxianjiage(null);
        	System.err.println("rules.jianmao.yimianjianmao:第一级价格有误");
        	return;
        }
        shangxianjiage = StringUtil.mul(firstShangxianjiage,1.0);
         //保留2位小数
        shangxianjiage = StringUtil.round(shangxianjiage,2);
        $record.setShangxianjiage(shangxianjiage);
end

//反正面剪毛
rule "fanzhengjianmao"
   	salience 98  
    lock-on-active true 
    when
         $record:Record(jianmaojiagongleibie2.equals("反正面剪毛"))
    then
         //上限价格
        double shangxianjiage = 0.0;
        //第一级上限价格
        Double firstShangxianjiage = $record.getShangxianjiage();
        if(firstShangxianjiage==null || firstShangxianjiage.doubleValue()<0.0){
        	$record.setShangxianjiage(null);
        	System.err.println("rules.jianmao.fanzhengjianmao:第一级价格有误");
        	return;
        }
        shangxianjiage = StringUtil.mul(firstShangxianjiage,1.8);
         //保留2位小数
        shangxianjiage = StringUtil.round(shangxianjiage,2);
        $record.setShangxianjiage(shangxianjiage);
end

//集团内部加工企业，上浮20%
rule "jituan"
   	salience 97  
    lock-on-active true 
    when
        $record:Record(isTrue(jianmaoshifoujituanneibu))
    then
         //上限价格
        double shangxianjiage = 0.0;
        //第一级上限价格
        Double secondShangxianjiage = $record.getShangxianjiage();
        if(secondShangxianjiage==null || secondShangxianjiage.doubleValue()<0.0){
        	$record.setShangxianjiage(null);
        	System.err.println("rules.jianmao.jituan:第二级价格有误");
        	return;
        }
        shangxianjiage = StringUtil.mul(secondShangxianjiage,1.2);
         //保留2位小数
        shangxianjiage = StringUtil.round(shangxianjiage,2);
        $record.setShangxianjiage(shangxianjiage);
end