package com.cmp.main.view.record.chengyi
 
import com.cmp.main.model.Record;
import com.cmp.core.common.StringUtil;
//是否是内衣
function boolean isNeiYi(String leibie){
	 if(StringUtil.isEmpty(leibie)){
	 	return false;
	 }
	 return leibie.equals("内衣");
}
function boolean isWaiYi(String leibie){
	 if(StringUtil.isEmpty(leibie)){
	 	return false;
	 }
	 return leibie.equals("外衣");
}
function boolean isTongLeiBie(String leibie){
	 if(StringUtil.isEmpty(leibie)){
	 	return false;
	 }
	 return leibie.equals("转同类别");
}
function boolean isBuTongLeiBie(String leibie){
	 if(StringUtil.isEmpty(leibie)){
	 	return false;
	 }
	 return leibie.equals("转不同类别");
}
//计算上限价格,基础价格*折标系数*（1+附加系数）
function double getShangXianJiaGe(double basePrice,double zhebiao,double fujia){
   	//保留两位小数
   	return StringUtil.round(StringUtil.mul(StringUtil.mul(basePrice,zhebiao),StringUtil.add(fujia,1)),2);
}
//计算附加系数
//内衣、同类别，1000件以内,附加系数0.5
rule "fujia1"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isNeiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang<1001)
    then
        $record.setFujiaxishu(0.5);
end

//内衣、同类别，1001--2000件,附加系数0.2
rule "fujia2"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isNeiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang>1000,shuliang<2001)
    then
        $record.setFujiaxishu(0.2);
end

//内衣、同类别，2001-3000件,附加系数0.1
rule "fujia3"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isNeiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang>2000,shuliang<3001)
    then
        $record.setFujiaxishu(0.1);
end

//内衣、同类别，3001-5000件,附加系数0.05
rule "fujia4"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isNeiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang>3000,shuliang<5001)
    then
        $record.setFujiaxishu(0.05);
end

//内衣、同类别，5000件以上,附加系数0
rule "fujia5"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isNeiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang>5000)
    then
        $record.setFujiaxishu(0.0);
end

//内衣、不同类别，1000件以内,附加系数0.8
rule "fujia6"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isNeiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang<1001)
    then
        $record.setFujiaxishu(0.8);
end

//内衣、不同类别，1001--2000件,附加系数0.5
rule "fujia7"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isNeiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang>1000,shuliang<2001)
    then
        $record.setFujiaxishu(0.5);
end

//内衣、不同类别，2001-3000件,附加系数0.3
rule "fujia8"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isNeiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang>2000,shuliang<3001)
    then
        $record.setFujiaxishu(0.3);
end

//内衣、不同类别，3001-5000件,附加系数0.2
rule "fujia9"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isNeiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang>3000,shuliang<5001)
    then
        $record.setFujiaxishu(0.2);
end

//内衣、不同类别，5000件以上,附加系数0
rule "fujia10"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isNeiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang>5000)
    then
        $record.setFujiaxishu(0.0);
end

//外衣、同类别，100件以内,附加系数0.7
rule "fujia11"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang<101)
    then
        $record.setFujiaxishu(0.7);
end

//外衣、同类别，101--300件,附加系数0.6
rule "fujia12"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang>100,shuliang<301)
    then
        $record.setFujiaxishu(0.6);
end

//外衣、同类别，301-500件,附加系数0.5
rule "fujia13"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang>300,shuliang<501)
    then
        $record.setFujiaxishu(0.5);
end

//外衣、同类别，501--1000件,附加系数0.4
rule "fujia14"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang>500,shuliang<1001)
    then
        $record.setFujiaxishu(0.4);
end

//外衣、同类别，1001--1500件,附加系数0.3
rule "fujia15"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang>1000,shuliang<1501)
    then
        $record.setFujiaxishu(0.3);
end

//外衣、同类别，1501--2000件,附加系数0.3
rule "fujia16"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang>1500,shuliang<2001)
    then
        $record.setFujiaxishu(0.3);
end

//外衣、同类别，2001-2500件,附加系数0.2
rule "fujia17"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang>2000,shuliang<2501)
    then
        $record.setFujiaxishu(0.2);
end

//外衣、同类别，2501-3000件,附加系数0.2
rule "fujia18"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang>2500,shuliang<3001)
    then
        $record.setFujiaxishu(0.2);
end

//外衣、同类别，3001-5000件,附加系数0.0
rule "fujia19"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang>3000,shuliang<5001)
    then
        $record.setFujiaxishu(0.0);
end

//外衣、同类别，5000件以上,附加系数0.0
rule "fujia20"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isTongLeiBie(zhuanleibie),shuliang>5000)
    then
        $record.setFujiaxishu(0.0);
end

//外衣、不同类别，100件以内,附加系数0.8
rule "fujia21"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang<101)
    then
        $record.setFujiaxishu(0.8);
end

//外衣、不同类别，101--300件,附加系数0.8
rule "fujia22"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang>100,shuliang<301)
    then
        $record.setFujiaxishu(0.8);
end

//外衣、不同类别，301-500件,附加系数0.8
rule "fujia23"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang>300,shuliang<501)
    then
        $record.setFujiaxishu(0.8);
end

//外衣、不同类别，501--1000件,附加系数0.8
rule "fujia24"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang>500,shuliang<1001)
    then
        $record.setFujiaxishu(0.8);
end

//外衣、不同类别，1001--1500件,附加系数0.5
rule "fujia25"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang>1000,shuliang<1501)
    then
        $record.setFujiaxishu(0.5);
end

//外衣、不同类别，1501--2000件,附加系数0.5
rule "fujia26"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang>1500,shuliang<2001)
    then
        $record.setFujiaxishu(0.5);
end

//外衣、不同类别，2001-2500件,附加系数0.3
rule "fujia27"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang>2000,shuliang<2501)
    then
        $record.setFujiaxishu(0.3);
end

//外衣、不同类别，2501-3000件,附加系数0.3
rule "fujia28"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang>2500,shuliang<3001)
    then
        $record.setFujiaxishu(0.3);
end

//外衣、不同类别，3001-5000件,附加系数0.2
rule "fujia29"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang>3000,shuliang<5001)
    then
        $record.setFujiaxishu(0.2);
end

//外衣、不同类别，5000件以上,附加系数0.0
rule "fujia30"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(isWaiYi(chanpinpinzhong),isBuTongLeiBie(zhuanleibie),shuliang>5000)
    then
        $record.setFujiaxishu(0.0);
end

//计算上限价格
rule "shangxianjiage"
   	salience 99  
    lock-on-active true 
    when
        $record:Record(!StringUtil.isEmpty(chanpinpinzhong))
    then
        //取附加系数
        Double fujia = $record.getFujiaxishu();
        //公司折标系数
        Double zhebiao = $record.getGszhebiaoxishu();
        //基础价格
        Double basePrice = $record.getBasePrice();
        if(fujia==null || zhebiao==null || basePrice==null){
        	System.err.println("rules.chengyi.shangxianjiage:基础数据有误，fujia："+fujia+",zhebiao:"+zhebiao+",basePrice:"+basePrice);
        	return;
        }
        $record.setShangxianjiage(getShangXianJiaGe(basePrice,zhebiao,fujia));
end