package com.cmp.main.view.record.dingxing
 
import com.cmp.main.model.Record;
import com.cmp.core.common.StringUtil;

function boolean isTrue(String str){
	if(!StringUtil.isEmpty(str) && str.equals("是")){
    	return true;
    }
    return false;
}
function boolean isFalse(String str){
	if(!StringUtil.isEmpty(str) && str.equals("否")){
    	return true;
    }
    return false;
}

//毛坯
rule "guangpi"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(dingxingpibupinzhong.equals("毛坯"))
    then
       $record.setBasePrice(1.8);
end

//光坯
rule "maopi"
   	salience 100  
    lock-on-active true 
    when
        $record:Record(dingxingpibupinzhong.equals("光坯"))
    then
       Double basePrice = StringUtil.mul(1.8,0.93);
       basePrice = StringUtil.round(basePrice,2);
       $record.setBasePrice(basePrice);
end

//由对方发送货，上浮10%
rule "duifangsonghuo"
   	salience 99  
    lock-on-active true 
    when
         $record:Record(isTrue(dingxingduifangsonghuo))
    then
        //基础价格
        Double basePrice = $record.getBasePrice();
        if(basePrice==null){
        	System.err.println("rules.dingxing.songhuo:基础价格为null");
        	return;
        }
        double shangxianjiage = 0.0;
        shangxianjiage = StringUtil.mul(basePrice.doubleValue(),1.1);
        //保留2位小数
        shangxianjiage = StringUtil.round(shangxianjiage,2);
        $record.setShangxianjiage(shangxianjiage);
end

//非对方发送货，*1
rule "feiduifangsonghuo"
   	salience 99  
    lock-on-active true 
    when
         $record:Record(isFalse(dingxingduifangsonghuo))
    then
        //基础价格
        Double basePrice = $record.getBasePrice();
        if(basePrice==null){
        	System.err.println("rules.dingxing.songhuo:基础价格为null");
        	return;
        }
        double shangxianjiage = 0.0;
        shangxianjiage = StringUtil.mul(basePrice.doubleValue(),1);
        //保留2位小数
        shangxianjiage = StringUtil.round(shangxianjiage,2);
        $record.setShangxianjiage(shangxianjiage);
end

//集团内部加工企业，上浮20%
rule "jituan"
   	salience 98  
    lock-on-active true 
    when
        $record:Record(isTrue(dingxingshifoujituanneibu))
    then
         //上限价格
        double shangxianjiage = 0.0;
        //第一级上限价格
        Double firstShangxianjiage = $record.getShangxianjiage();
        if(firstShangxianjiage==null || firstShangxianjiage.doubleValue()<0.0){
        	$record.setShangxianjiage(null);
        	System.err.println("rules.dingxing.jituan:第一级价格有误");
        	return;
        }
        shangxianjiage = StringUtil.mul(firstShangxianjiage,1.2);
         //保留2位小数
        shangxianjiage = StringUtil.round(shangxianjiage,2);
        $record.setShangxianjiage(shangxianjiage);
end