//created on: 2014-5-12
//公用方法
package com.cmp.main.view.record.xiuhua

import com.cmp.core.common.StringUtil;
import java.util.Arrays;
import com.cmp.main.model.Record;

	//是否贴布绣
	function boolean isTieBu(String leibie){
		 if(StringUtil.isEmpty(leibie)){
		 	return false;
		 }
		 String[] leibies = new String[]{"贴布绣单层","贴布绣多层（上下一样）","贴布绣多层（上下不一样）","贴布绣手剪"};
		 return Arrays.asList(leibies).indexOf(leibie)!=-1;
	}
	//是否平绣
	function boolean isPingXiu(String leibie){
		 if(StringUtil.isEmpty(leibie)){
		 	return false;
		 }
		 return leibie.equals("平绣");
	}
	//是否毛巾绣
	function boolean isMaoJinXiu(String leibie){
		 if(StringUtil.isEmpty(leibie)){
		 	return false;
		 }
		 return leibie.equals("毛巾绣");
	}
	//是否羊毛绣
	function boolean isYangMaoXiu(String leibie){
		 if(StringUtil.isEmpty(leibie)){
		 	return false;
		 }
		 return leibie.equals("羊毛绣");
	}
	//是否金线银线刺绣
	function boolean isJxYxCiXiu(String leibie){
		 if(StringUtil.isEmpty(leibie)){
		 	return false;
		 }
		 return leibie.equals("金线银线刺绣");
	}
	//是否亮片绣
	function boolean isLiangPianXiu(String leibie){
		 if(StringUtil.isEmpty(leibie)){
		 	return false;
		 }
		 return leibie.equals("亮片绣");
	}
	//是否印花刺绣
	function boolean isYinHuaCiXiu(String leibie){
		 if(StringUtil.isEmpty(leibie)){
		 	return false;
		 }
		 return leibie.equals("印花刺绣");
	}
	//是否普通绣
	function boolean isPuTongXiu(String leibie){
		 if(StringUtil.isEmpty(leibie)){
		 	return false;
		 }
		 return leibie.equals("普通绣");
	}
	//是否隔头绣、是否先绣标
	function boolean isTrue(String str){
		if(!StringUtil.isEmpty(str) && str.equals("是")){
	    	return true;
	    }
	    return false;
	}
	//隔头绣上浮比例
	function double getGeTouBiLi(){
		return 1.3;
	}
	//小数精确位数
	function int getXiaoShu(){
		return 2;
	}
	//千针数价格计算方法
	function double getBasePrice(double price,int zhenshu){
        double p = StringUtil.div(price,1000);
        return StringUtil.round(StringUtil.mul(p,zhenshu),getXiaoShu());
	}
